---
driver:
  name: docker

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    driver_config:
      image: pingworks/docker-ws-baseimg:0.2
      # revert the STEP1 changes from kitchen docker
      provision_command: rm /sbin/initctl; dpkg-divert --local --rename --remove /sbin/initctl
      # and run init instead of sshd
      run_command: /sbin/init

suites:
  - name: jkmaster
    run_list:
      - recipe[pw_testhelper]
      - recipe[env_ws_pipeline::jkmaster]
    attributes:
      pw_base:
        skip-hosts: true
        domain: local
        basedomain: local
      pw_chefdk:
        chefdk:
          url: 'https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/12.04/x86_64/chefdk_0.7.0-1_amd64.deb'
      env_ws_pipeline:
        jenkins-config: 'demo'
    driver:
      hostname: jkmaster.local
      instance_name: jkmaster

  - name: jkslave
    run_list:
      - recipe[pw_testhelper]
      - recipe[env_ws_pipeline::jkslave]
    attributes:
      pw_base:
        skip-hosts: true
        domain: local
        basedomain: local
      pw_jenkins:
        slave:
          master_url: 'http://jkmaster:8080/jenkins'
          name: 'jkslave'
    driver:
      hostname: jkslave.local
      instance_name: jkslave
      links:
        jkmaster:jkmaster
