---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.4.1

platforms:
  - name: ubuntu-14.04
    driver:
      box: trusty-server-cloudimg-amd64-vagrant-disk1
      box_url: https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box

suites:
  - name: jkmaster
    run_list:
      - recipe[pw_testhelper]
      - recipe[env_ws_pipeline::jkmaster]
    attributes:
      pw_chefdk:
        chefdk:
          url: 'https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/12.04/x86_64/chefdk_0.7.0-1_amd64.deb'
    driver:
      network:
        - [ 'forwarded_port', { guest: 80, host: 1080 } ]
        - [ 'private_network', { ip: '192.168.88.100' } ]
  - name: jkslave
    run_list:
      - recipe[pw_testhelper]
      - recipe[env_ws_pipeline::jkslave]
    attributes:
      pw_jenkins:
        slave:
          master_url: 'http://192.168.88.100:8080/jenkins'
          name: 'jkslave'
    driver:
      network:
        - [ 'private_network', { ip: '192.168.88.200' } ]
