name             'env_ws_pipeline'
maintainer       'Christoph Lukas'
maintainer_email 'christoph.lukas@gmx.net'
license          'All rights reserved'
description      'Environment cookbook for a basic pipeline'
long_description 'Environment cookbook for a basic pipeline'
version          '0.2.0'

depends 'pw_base', '=0.2.0'
depends 'pw_jenkins', '=0.2.0'
depends 'pw_chefdk', '=0.2.0'
depends 'pw_openstack_clients', '=0.2.0'
depends 'pw_mofa', '=0.2.0'
depends 'pw_cookbook_repo', '=0.2.0'
depends 'pw_testhelper', '=0.2.0'
depends 'chef-dash', '=0.3.7'
depends 'pw_git_repo', '=0.2.0'
depends 'ws_phonebook', '=0.2.0'
