name             'ws-env-pipeline'
maintainer       'Christoph Lukas'
maintainer_email 'christoph.lukas@gmx.net'
license          'All rights reserved'
description      'Environment cookbook for a basic pipeline'
long_description 'Environment cookbook for a basic pipeline'
version          '0.1.0'

depends 'pw_base'
depends 'pw_jenkins'
depends 'pw_chefdk'
depends 'pw_openstack_clients'
depends 'pw_mofa'
depends 'pw_cookbook_repo'
depends 'pw_testhelper'
depends 'chef-dash'
depends 'pw_git_repo'
depends 'ws-phonebook'
